# Generated by Django 4.0.10 on 2023-11-13 21:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('discovery', models.BooleanField(default=False)),
                ('rating', models.FloatField(default=0.0)),
                ('votes', models.IntegerField(default=0)),
                ('voters', models.ManyToManyField(blank=True, related_name='voted_locations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_name', models.CharField(max_length=200)),
                ('premade', models.BooleanField(default=True)),
                ('selected', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('locations', models.ManyToManyField(to='users.location')),
            ],
        ),
    ]
